name: CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - name: Set up environment variables
        run: |
          export NODE_ENV=test
          export MYSQL_HOST=${{ secrets.MYSQL_HOST }}
          export MYSQL_PORT=${{ secrets.MYSQL_PORT }}
          export MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
          export MYSQL_USER=${{ secrets.MYSQL_USER }}
          export MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
          echo "NODE_ENV=development" >> $GITHUB_ENV
          echo "MYSQL_HOST=$YOUR_MYSQL_HOST" >> $GITHUB_ENV
          echo "MYSQL_PORT=$YOUR_MYSQL_PORT" >> $GITHUB_ENV
          echo "MYSQL_DATABASE=$YOUR_MYSQL_DATABASE" >> $GITHUB_ENV
          echo "MYSQL_USER=$YOUR_MYSQL_USER" >> $GITHUB_ENV
          echo "MYSQL_PASSWORD=$YOUR_MYSQL_PASSWORD" >> $GITHUB_ENV 
          npm test
        env:
          NODE_ENV: test
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
