name: Unit Testing

on:
  push:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v4

      - name: setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Run Tests
        run: |
          export NODE_ENV=test
          export MYSQL_HOST=${{ secrets.TEST_MYSQL_HOST }}
          export MYSQL_PORT=${{ secrets.TEST_MYSQL_PORT }}
          export MYSQL_DATABASE=${{ secrets.TEST_MYSQL_DATABASE }}
          export MYSQL_USER=${{ secrets.TEST_MYSQL_USER }}
          export MYSQL_PASSWORD=${{ secrets.TEST_MYSQL_PASSWORD }}
          yarn test

      - name: server
        uses: easingthemes/ssh-deploy@v4
        with:
          SSH_PRIVATE_KEY: ${{ secrets.FTP_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.FTP_HOST }}
          REMOTE_USER: ${{ secrets.FTP_USER }}
          TARGET: ${{ secrets.FTP_TARGET }}
          run: |
            cd ${{ secrets.FTP_TARGET }}
            pm2 stop GoingMerry
            yarn
            pm2 restart GoingMerry
